### PR TITLE
Update all fonts, not just default font.

### PR DESCRIPTION
**Pull request by de-vri-es**

### CODE REVIEW

**Comment by simmel** [comment]
Sweet and thanks for the patch!

When we deal with that many font variants the code doesn't become very DRY.
Maybe you could make the code use an hash of hashes which has the font variant name as key, e.g. boldFont, and the size and ANSI number (whatever it's called), 711 in the bold case, and loop over it?

Example code:

``` perl
my @fonts = qw(font boldFont italicFont boldItalicFont);
my %font_sizes;

sub on_start {
  for (my $i=0; $i<=$#fonts; $i++) {
    $font_sizes{$fonts[$i]}{'size'} = $_[0]->resource($fonts[$i]);
    $font_sizes{$fonts[$i]}{'ansi'} = 710 + $i;
  }
}
```

BR,
- Simon

**Comment by de-vri-es** [comment]
Yeah I figured it was a bit repetitive, but I really don't know perl that well. Worth a try though.

**Comment by de-vri-es** [comment]
Righty, as far as I understood perl, this should do it.

**Comment by de-vri-es** [comment]
What do you think, ready for merging now?

**Comment by simmel** [comment]
Hey @de-vri-es sorry for the long delay!

I've tried the patch now and it seems to print the font and it's sizes two times when doing the "show" command?

Also, please squash the commits (so it only becomes one commit).

Maybe my example code was confusing but you can skip using the array and just use a hash which makes to code more readable and saner IMO:

``` perl
foreach ('font', 'boldFont', 'italicFont', 'boldItalicFont') {
  $fonts{$_} = {
      'default' => $self->resource($_),
      'code'    => 710 + $i
  };
  # Or even just this, depending on your style
  # $fonts{$_}{'default'} = "\$self->resource($_)";
  # $fonts{$_}{'code'} = 710 + $i;
  ++$i;
} 
```

**Comment by de-vri-es** [comment]
Hey,

I deliberately decided to use an array rather than a hash table, since the only type of access to the fonts is looping all of them. Specifically, they're never lookup up by name since the entire point was to do everything for every font. So I figured a list of hashes made more sense than a hash of hashes.

However, I did change the construction of the array slightly to something I myself find more appealing. See the last commit.

In general I'm not a fan of squashing commits, but you're right that in this case the commits are all related and are all tiny. I'll squash them after you've commented on the last commit though, so you can easily see what it changed.

Edit: on second thought, I'll just squash it now and if you really disagree with using an array of hashes rather than a hash of hashes, could you just merge it and then patch it yourself?

**Comment by de-vri-es** [comment]
Oh, and about the show command showing fonts twice, it just prints them all once for me. What exactly is it doing for you (screenshot might help)?

**Comment by de-vri-es** [comment]
ping?

**Comment by simmel** [comment]
Hey @de-vri-es! Real sorry about the delay again = /

I can't get it to work at all. I'm on Ubuntu Trusty and urxvt 9.19.

What's your urxvt config and with what shell commands can I reproduce to see the difference of bold and italic fonts?

**Comment by de-vri-es** [comment]
Hey, this should work to get normal, bold, italic and boldItalic text in urxvt:

```
printf '\e[0m%s \e[1m%s \e[0;3m%s \e[1;3m%s \e[0m\n' normal bold italic boldItalic
```

Note that you may need to configure an italic font before italic and boldItalic work.

**Comment by simmel** [comment]
Ah, that's what I used too.

Mind pasting your urxvt config?

If I use this in my `.Xresources`:

```
urxvt.font: xft:Inconsolata:pixelsize=12
```

and use my code; all font variations - bold, italic, etc - works as expected:
master one font

---

But if I specify a font for each font variation like this:

```
urxvt.font: xft:Inconsolata:pixelsize=12
urxvt.boldFont: xft:Inconsolata:bold:pixelsize=12
urxvt.italicFont: xft:Inconsolata:italic:pixelsize=12
urxvt.boldItalicFont: xft:Inconsolata:italic:bold:pixelsize=12
```

I get:
master specifying font variations

---

If I on the other hand use your patch and specify each font variation I get:
patch specifying font variations

---

But if I just use one font (which is what I do currently) I get no font variations at all:
patch one font

---

Does specifying just one font work for you? If not, what's your use case?

**Comment by de-vri-es** [comment]
Interesting. I'll see if I can get it to work for all configurations.

**Comment by de-vri-es** [comment]
That commit seems to fix it for all configurations. Fonts that have not been set explicitly will not be touched anymore. I can squash if you like.

**Comment by simmel** [comment]
Thanks for your contribution and patience @de-vri-es!

**Comment by de-vri-es** [comment]
no problem, thanks for the extra info and the merge

**Pull request closed without merging**
