### PR TITLE
More information to where to put the script

### PR DESCRIPTION
**Pull request by edn9**
Path to put the script perl.

### CODE REVIEW

**Comment by simmel** [comment]
I've thought about this before but I never did somthing about it: should we update the instructions in the script or remove them all together?

What's your opintion?

**Comment by edn9** [comment]
I think its a nice idea because, like me, some users cant really figureout where to put (started users), I was like, searching and trying for very long until i realized. Also im gonna try urxvt and this script in others distro to see if the path is the same and I will update for you.

**Comment by simmel** [comment]
It can also change between versions. When I resurrected my `.Xresources` from my config repo I saw that I had configured `~/.urxvt/perl/` in 2009 or so. So it can change even if slowly.

That's why pointing to the man-page is so good because that will/should always be up to date :ok_hand:

But maybe, like you suggest, giving an example of where to put it but also noting that the truth lies in the `urxvt(1)` man-page on `perl-lib` is the way to go. What do you think?

**Comment by edn9** [comment]
Lets have both ;D

> perl-lib: path
>            Colon-separated list of additional directories that hold extension
>            scripts. When looking for perl extensions, urxvt will first look in
>            these directories, then in $URXVT_PERL_LIB, $HOME/.urxvt/ext and
>            lastly in /usr/lib/urxvt/perl/.
>

**Comment by simmel** [comment]
Ok then!

Update your PR with man-page stuff from the README then.

Thanks!

**Comment by edn9** [comment]
Done here and in the readme.md!

**Comment by simmel** [comment]
I was thinking more something like:

```
Put the resize-font script where urxvt searches for perl libs, e.g. $HOME/.urxvt/ext/. For exact path see urxvt(1) man-page on perl-lib.
```

**Comment by edn9** [comment]
Done. Check out the pull requests.

**Comment by simmel** [comment]
I reworded and made it even more uniform. Thank you for the contribution!

**Pull request closed without merging**
