### PR TITLE
Fix bug when font name includes numeric characters

### PR DESCRIPTION
**Pull request by syusui-s**
Fixed a bug.
When font name includes numeric characters, a regex in `update_font_size` matches it.
I changed the regex.

### CODE REVIEW

**Comment by simmel** [comment]
Thank you for the contribution!

I've been trying to look at the official documentation if there is a difference between `pixelsize` and `size` but I haven't found anything. Do you know?

I just have to test it on my laptop at home and I'll merge it.

**Comment by simmel** [comment]
Ah, it seems to be an XFT thing, see http://linux.die.net/man/5/fonts-conf on in the table under the headline "FONT PROPERTIES".

Basically it's `pt` vs. `px`.

**Comment by syusui-s** [comment]
Thanks for your reply! 

I didn't know the difference well, but I've seen some samples on [Arch Wiki](https://wiki.archlinux.org/index.php/Rxvt-unicode#Font_declaration_methods) and used `size` in my Xresource. 

I saw the page. the regex supports both settings
(a variable length lookbehind such as `qr"(?<=size=|pixelsize=)"` is
not implemented in Perl unfortunately, I think there is no better way).

**Comment by syusui-s** [comment]
Thanks you for the merge! :smile:

**Pull request closed without merging**
